{{ if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsbot.fullname" . }}-persistence
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  {{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName }}
  {{- end }}
{{ end }}